/**
 * @desc 掘金markdown主题
 * @source https://github.com/xitu/juejin-markdown-themes
 */
export const themes = {
  juejin: {
    owner: 'xitu',
    repo: 'juejin-markdown-theme-default',
    path: 'juejin.scss',
    ref: '195cbb0',
    highlight: 'juejin',
  },
  github: {
    owner: 'sindresorhus',
    repo: 'github-markdown-css',
    path: 'github-markdown.css',
    ref: '888d5a0',
    highlight: 'github',
  },
  smartblue: {
    owner: 'cumt-robin',
    repo: 'juejin-markdown-theme-smart-blue',
    path: 'smart-blue.css',
    ref: 'f266ca5',
  },
  cyanosis: {
    owner: 'linxsbox',
    repo: 'juejin-markdown-theme-cyanosis',
    path: 'cyanosis.scss',
    ref: '6b814ea',
    highlight: 'atom-one-dark',
  },
  'channing-cyan': {
    owner: 'ChanningHan',
    repo: 'juejin-markdown-theme-channing-cyan',
    path: 'channing-cyan.scss',
    ref: 'c843c2f',
  },
  fancy: {
    owner: 'xrr2016',
    repo: 'juejin-markdown-theme-fancy',
    path: 'fancy.scss',
    ref: 'eeeb566',
  },
  hydrogen: {
    owner: 'DawnLck',
    repo: 'juejin-markdown-theme-hydrogen',
    path: 'hydrogen.scss',
    ref: 'b3f86fb',
  },
  'condensed-night-purple': {
    owner: 'Geekhyt',
    repo: 'condensed-night-purple',
    path: 'condensed-night-purple.scss',
    ref: '4f50a4f',
  },
  greenwillow: {
    owner: 'wangly19',
    repo: 'juejin-markdown-theme-greenwillow',
    path: 'greenwillow.scss',
    ref: 'aca95ed',
  },
  'v-green': {
    owner: 'DawnLck',
    repo: 'juejin-markdown-theme-v-green',
    path: 'v-green.scss',
    ref: '015f88b',
  },
  'vue-pro': {
    owner: 'dunizb',
    repo: 'juejin-markdown-theme-vue-pro',
    path: 'vue-pro.scss',
    ref: '720e7a9',
    highlight: 'monokai',
  },
  'healer-readable': {
    owner: 'healerLZH',
    repo: 'juejin-markdown-theme-healer-readable',
    path: 'healer-readable.scss',
    ref: '3f2ef56',
    highlight: 'srcery',
  },
  'mk-cute': {
    owner: 'Jacky-Summer',
    repo: 'juejin-markdown-theme-mk-cute',
    path: 'mk-cute.scss',
    ref: '50d6414',
  },
  jzman: {
    owner: 'jzmanu',
    repo: 'juejin-markdown-theme-jzman',
    path: 'jzman.scss',
    ref: 'b8cf058',
    highlight: 'monokai',
  },
  'geek-black': {
    owner: 'MageeLin',
    repo: 'juejin-markdown-theme-geek-black',
    path: 'geek-black.scss',
    ref: '888136c',
    highlight: 'monokai',
  },
  'awesome-green': {
    owner: 'luffyZh',
    repo: 'juejin-markdown-theme-awesome-green',
    path: 'awesome-green.scss',
    ref: '5e8259b',
  },
  'qklhk-chocolate': {
    owner: 'QiaokeliHenku',
    repo: 'juejin-markdown-theme-qkl',
    path: 'chocolate.scss',
    ref: '8bbb87d',
  },
};

/**
 * @desc highlight主题
 * 来源 highlight.js 项目
 * css文件保存在本地，此处为highlight主题配置，对应css文件在public/css/highlight目录下
 * @source https://github.com/highlightjs/highlight.js
 */
export const highlights = [
  'default',
  'a11y-dark',
  'a11y-light',
  'agate',
  'an-old-hope',
  'androidstudio',
  'arduino-light',
  'arta',
  'ascetic',
  'atelier-cave-dark',
  'atelier-cave-light',
  'atelier-dune-dark',
  'atelier-dune-light',
  'atelier-estuary-dark',
  'atelier-estuary-light',
  'atelier-forest-dark',
  'atelier-forest-light',
  'atelier-heath-dark',
  'atelier-heath-light',
  'atelier-lakeside-dark',
  'atelier-lakeside-light',
  'atelier-plateau-dark',
  'atelier-plateau-light',
  'atelier-savanna-dark',
  'atelier-savanna-light',
  'atelier-seaside-dark',
  'atelier-seaside-light',
  'atelier-sulphurpool-dark',
  'atelier-sulphurpool-light',
  'atom-one-dark-reasonable',
  'atom-one-dark',
  'atom-one-light',
  'brown-paper',
  'codepen-embed',
  'color-brewer',
  'darcula',
  'dark',
  'default',
  'docco',
  'dracula',
  'far',
  'foundation',
  'github-gist',
  'github',
  'gml',
  'googlecode',
  'gradient-dark',
  'grayscale',
  'gruvbox-dark',
  'gruvbox-light',
  'hopscotch',
  'hybrid',
  'idea',
  'ir-black',
  'isbl-editor-dark',
  'isbl-editor-light',
  'kimbie.dark',
  'kimbie.light',
  'lightfair',
  'magula',
  'mono-blue',
  'monokai-sublime',
  'monokai',
  'night-owl',
  'nord',
  'obsidian',
  'ocean',
  'paraiso-dark',
  'paraiso-light',
  'pojoaque',
  'purebasic',
  'qtcreator_dark',
  'qtcreator_light',
  'railscasts',
  'rainbow',
  'routeros',
  'school-book',
  'shades-of-purple',
  'solarized-dark',
  'solarized-light',
  'srcery',
  'stackoverflow-dark',
  'stackoverflow-light',
  'sunburst',
  'tomorrow-night-blue',
  'tomorrow-night-bright',
  'tomorrow-night-eighties',
  'tomorrow-night',
  'tomorrow',
  'vs',
  'vs2015',
  'xcode',
  'xt256',
  'zenburn',
];
